// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zocfidzghjioaebpwdgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvY2ZpZHpnaGppb2FlYnB3ZGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzM5NTEsImV4cCI6MjA2NDgwOTk1MX0.SORRA1rFH7sOSR-0mZTVKHwYOPrjHfOWE_SC1I3S950";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);